import jsPDF from 'jspdf';
import { Unit, Parcel, Building } from '../types';

export function exportPropertyPDFReport(unit: Unit, parcel?: Parcel, building?: Building) {
    const doc = new jsPDF();

    // Header styling
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.text('BHUMI3D', 14, 22);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('3D Cadastral Digital Property Record (DPI)', 14, 30);

    doc.setTextColor(56, 189, 248); // cyan-400
    doc.text('PROTOTYPE PROPERTY ID', 140, 22);

    // Body content
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Vertical Property Passport', 14, 52);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'mono');
    doc.text(`VPID: ${unit.unitUid}`, 14, 62);

    doc.setDrawColor(203, 213, 225);
    doc.line(14, 68, 196, 68);

    // Key Value Table
    const startY = 78;
    const rowH = 10;
    const data = [
        ['Land Parcel ULPIN:', parcel?.parcelUid || 'TN-CHN-TRP-00018427'],
        ['Survey Plot Number:', parcel?.surveyNumber || '184/27A'],
        ['Administrative Location:', `${parcel?.village || 'Tambaram East'}, ${parcel?.taluk || 'Tambaram'}, ${parcel?.district || 'Chennai'}`],
        ['Building Identity:', `${building?.buildingName || 'Bhumi Residency Tower A'} (${building?.buildingUid || 'B01'})`],
        ['Floor Level & Unit Number:', `Floor 8 — Unit ${unit.unitNumber}`],
        ['Unit Property Type:', unit.unitType],
        ['Carpet Area:', `${unit.areaSqft} sq.ft`],
        ['Occupancy & Masked Owner:', `${unit.occupancyStatus} (${unit.ownerNameMasked})`],
        ['Geospatial Validation:', 'TURF.JS TOPOLOGY VALIDATED — 0 CONFLICTS'],
        ['Verification Badge:', 'APPROVED DIGITAL PUBLIC INFRASTRUCTURE RECORD']
    ];

    doc.setFont('helvetica', 'normal');
    data.forEach((row, i) => {
        const y = startY + (i * rowH);
        doc.setFont('helvetica', 'bold');
        doc.text(row[0], 14, y);
        doc.setFont('helvetica', 'normal');
        doc.text(row[1], 80, y);
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text('Generated by BHUMI3D Cadastral Infrastructure Engine. Verified by Ministry of Urban Land Records.', 14, 280);

    doc.save(`BHUMI3D_Property_${unit.unitNumber}.pdf`);
}
